### ISSUE TITLE
Deprecated selector in `space-deep/styles/space-deep.atom-text-editor.less`

### ISSUE THREAD

**Issue by molk** [lts123124/space-deep#1]
In `space-deep/styles/space-deep.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-2` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-2`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-4` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-4`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-6` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-6`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-8` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-8`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-10` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-10`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-12` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-12`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-14` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-14`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-16` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-16`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-18` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-18`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-20` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-20`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-22` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-22`

* `atom-text-editor::shadow .gutter .line-number.line-number-sdp-24` => `atom-text-editor.editor .gutter .line-number.line-number-sdp-24`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by lts123124** [comment]
Thanks for your report, plugin updated
